PLUS = 'PLUS'
MINUS = 'MINUS'
MUL = 'MUL'
DIV = 'DIV'
NOT_EQUAL = 'NOT_EQUAL'
EQUAL = 'EQUAL'
NOT = 'NOT'
COMMA = 'COMMA'
SEMICOLON = 'SEMICOLON'
OPEN_PAREN = 'OPENPAREN'
CLOSE_PAREN = 'CLOSEPAREN'
LESS_THAN = 'LESS_THAN'
LESS_OR_EQUAL = 'LESS_OR_EQUAL'
GREATER_THAN = 'GREATER_THAN'
GREATER_OR_EQUAL = 'GREATER_OR_EQUAL'
ASSIGNMENT = 'ASSIGNMENT'
UNKNOWN = 'UNKNOWN'
INTEGER = 'INTEGER'
FLOAT = 'FLOAT'
STRING = 'STRING'
IDENTIFIER = 'IDENTIFIER'
FUNC = 'FUNC'
IF = 'IF'
THEN = 'THEN'
RET = 'RET'
END = 'END'
ELSE = 'ELSE'
WHILE = 'WHILE'
DO = 'DO'

keywords = {
    'func': FUNC,
    'if': IF,
    'then': THEN,
    'ret': RET,
    'end': END,
    'else': ELSE,
    'while': WHILE,
    'do': DO
}
